### ISSUE TITLE
Aoe2De new features make bugs

### ISSUE THREAD

**Issue by gd1446056618** [SiegeEngineers/genieutils-py#1]
A new serialize form about dropsite make bugs.
unit.py need some change

# drop_sites = content.read_int_16_array_3()
drop_sites_count = content.read_int_16()
drop_sites = content.read_int_16_array(drop_sites_count)
...
drop_sites_count=drop_sites_count,
...
self.write_int_16(self.drop_sites_count),

**Comment by HSZemi** [comment]
Thank you for your report. Version 0.0.4 has just been released, which is compatible with both FileVersion 7.7 and the new FileVersion 7.8.
